language: python

python:
  - 3.6

env:
  - travis_ci_mode=true

install:
  - pip install -r requirements.txt
  - pip install -e .

script:
  # run tests
  - python3 -m unittest tests/*.py -v
  # run examples
  - python3 examples/*.py